/* Static visual specification. No production imports, API calls or external sends. */
const params = new URLSearchParams(location.search);
const pageName = params.get('page') || 'home';
document.documentElement.dataset.theme = params.get('theme') === 'dark' ? 'dark' : 'light';
const asset = name => `assets/${name}`;
const href = page => `reference.html?page=${page}&theme=${document.documentElement.dataset.theme}`;
const icons = {
 moon:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M20.3 15.4A8.8 8.8 0 0 1 8.6 3.7a8.8 8.8 0 1 0 11.7 11.7Z"/></svg>',
 sun:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>',
 menu:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 8h16M4 16h16"/></svg>',
 wa:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M20 11.5a8 8 0 0 1-11.8 7L4 20l1.4-4.1A8 8 0 1 1 20 11.5Z"/><path d="M9 7.8c-.8.3-.9 1.5-.2 2.8 1.1 2.2 2.4 3.4 4.4 4.2 1.5.6 2.6 0 2.7-.8l-2.3-1.4-1.1.8a8 8 0 0 1-2.7-2.8l.7-1-1.5-1.8Z"/></svg>',
 shop:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor"><path d="M8 20v22h32V20M5 19l5-13h28l5 13M5 19c0 7 9 7 9 0 0 7 10 7 10 0 0 7 10 7 10 0 0 7 9 7 9 0M18 42V29h12v13M15 6l-1 13M24 6v13M33 6l1 13"/></svg>',
 truck:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor"><path d="M4 10h26v25H4ZM30 20h8l6 9v6H30M35 21v9h8"/><circle cx="13" cy="36" r="5"/><circle cx="36" cy="36" r="5"/></svg>',
 arch:'<svg viewBox="0 0 48 48" fill="none" stroke="currentColor"><path d="M7 42V6h34v36M14 42V16h20v26M4 42h13m14 0h13M7 10h34"/></svg>'
};
const logo = (className='') => `<img class="${className}" src="${asset('adjeet-original.png')}" width="586" height="175" alt="AD-JEET, since 1990">`;
const quote = (label='WhatsApp your project', extra='') => `<a class="button ${extra}" href="${href('contact')}">${icons.wa}<span>${label}</span><span class="arrow" aria-hidden="true">↗</span></a>`;
const nav = () => `<header class="header"><a class="brand" href="${href('home')}" aria-label="AD-JEET home">${logo()}</a><nav class="desktop-nav" aria-label="Main"><a href="${href('work')}">Our work</a><a href="${href('services')}">Services</a><a href="${href('about')}">About us</a><a class="nav-quote" href="${href('contact')}">Start a project ↗</a></nav><div class="header-actions"><button class="icon-button theme-button" id="theme" aria-label="Switch to night theme">${icons.moon}</button><button class="icon-button menu-button" id="menu" aria-label="Open menu" aria-expanded="false" aria-controls="menu-panel">${icons.menu}</button></div></header><nav class="menu-panel" id="menu-panel" aria-label="Mobile" hidden>${[['home','Home'],['work','Our work'],['services','Services'],['about','About us'],['contact','Contact']].map(([p,label])=>`<a href="${href(p)}">${label}<span aria-hidden="true">↗</span></a>`).join('')}${quote('Start a project')}</nav>`;
const footer = () => `<footer class="footer"><a class="brand" href="${href('home')}">${logo()}</a><div class="footer-info"><p>Signage. Print. Outdoor branding.<br><span class="muted">Siliguri, North Bengal.</span></p><a href="${href('contact')}">+91 98320 11524 ↗</a></div><nav class="footer-links" aria-label="Footer">${[['services','Services'],['work','Our work'],['about','About us'],['contact','Contact'],['privacy','Privacy']].map(([p,label])=>`<a href="${href(p)}">${label}</a>`).join('')}</nav><small>AD-JEET · Established 1990</small></footer>`;
const enquiry = () => `<section class="enquiry-section"><h2>What are we putting your name on?</h2><p>Send a photo of your space.<br>Tell us where it is. Let’s start there.</p>${quote('WhatsApp your project')}</section>`;
const sticky = () => `<aside class="sticky-enquiry" id="sticky">${quote()}</aside>`;
const projects = [
 {image:'Ambuja_cement_ACP-LED.png',name:'Ambuja Cement',type:'ACP & LED signage',filter:'signage'},
 {image:'SRMB_vechile.png',name:'SRMB',type:'Vehicle branding',filter:'vehicles'},
 {image:'Acc.png',name:'ACC Cement',type:'Outdoor signage',filter:'signage'},
 {image:'Gates.png',name:'Gates',type:'Brand signage',filter:'signage'},
 {image:'airtel.png',name:'Airtel',type:'Glow sign board',filter:'signage'}
];
const project = (p,cls='') => `<figure class="project ${cls}" data-filter="${p.filter}"><a href="${asset(p.image)}" target="_blank" rel="noopener" aria-label="View ${p.name} project photo"><img src="${asset(p.image)}" alt="${p.name}, ${p.type}" loading="lazy"></a><figcaption><div><strong>${p.name}</strong><p>${p.type}</p></div><span class="arrow" aria-hidden="true">↗</span></figcaption></figure>`;
const services = [
 ['Glow Sign Boards','Illuminated faces for shopfronts and business signs.','storefront'],
 ['ACP & LED Signage','Clean façades, precise lettering and a considered finish.','storefront'],
 ['One-Way Vision','Printed glass graphics for your storefront or vehicle.','storefront'],
 ['Flex Printing','Banners, backdrops and large-format campaign print.','campaign'],
 ['Vehicle Branding','Put your identity on the road, from one van to a fleet.','campaign'],
 ['Wall Painting','Painted brand communication for outdoor walls.','campaign'],
 ['F-Pole Installation','Fabricated roadside display structures.','campaign'],
 ['In-Shop Branding','From counter fronts to complete retail interiors.','space'],
 ['Events & Puja Decoration','Backdrops, entrance arches and celebration branding.','space'],
 ['Product Display','Custom displays for your products and retail spaces.','space']
];
function hero(){return `<section class="hero" aria-label="AD-JEET signage workshop concept"><div class="scene-plane" id="scene-plane"><picture><source media="(min-width:1024px)" srcset="${asset('hero-desktop-day.webp')}"><img src="${asset('hero-day.webp')}" alt="" fetchpriority="high"></picture><picture class="night-layer"><source media="(min-width:1024px)" srcset="${asset('hero-desktop-night.webp')}"><img src="${asset('hero-night.webp')}" alt=""></picture>${logo('scene-logo')}</div><div class="hero-scrim day"></div><div class="hero-scrim night"></div><span class="scene-caption">Brand concept</span><div class="hero-copy"><p class="eyebrow">Siliguri · Since 1990</p><h1>Made to<br>be seen.</h1><p class="lead">Signage, print & outdoor branding.<br>Designed. Fabricated. Installed.</p>${quote()}</div><a class="hero-more" href="#work">See what we make <span>↓</span></a></section><a class="scroll-note" href="#work"><span>Out on the street. In our work.</span><span class="arrow">↓</span></a>`}
function home(){return `${hero()}<section class="section wrap" id="work"><div class="section-head"><div><p class="eyebrow muted">Selected work</p><h2 style="margin-top:14px">You’ve probably<br>seen our work.</h2></div></div><div class="proof-layout">${project(projects[0],'proof-lead')}<div class="proof-secondary">${project(projects[1])}${project(projects[2])}</div></div><a class="text-link work-link" href="${href('work')}">Explore our work <span class="arrow">↗</span></a></section><section class="section canvas-section"><div class="wrap"><div class="section-head"><div><p class="eyebrow muted">What we make</p><h2 style="margin-top:14px">Choose your<br>canvas.</h2></div></div><div class="canvas-list">${[['Your storefront','Glow signs, ACP façades and window graphics.','shop'],['Your next campaign','Vehicle wraps, outdoor signs, wall painting and print.','truck'],['Your space or event','Shop interiors, product displays and event branding.','arch']].map(([t,p,i])=>`<a class="canvas-row" href="${href('services')}"><div><h3>${t} ↗</h3><p>${p}</p></div><span class="canvas-icon" aria-hidden="true">${icons[i]}</span></a>`).join('')}<a class="text-link work-link" href="${href('services')}">All 10 services <span>↗</span></a></div></div></section><section class="material-section"><img class="material-visual" src="${asset('materials.webp')}" alt="Concept study of cyan acrylic, yellow vinyl, aluminium and LED modules" loading="lazy"><div class="material-copy"><p class="eyebrow">The craft behind the sign</p><h2>Built from<br>the inside out.</h2><p>A visible result starts with the right material, the right fit and attention to the finish.</p><div class="process"><div><span>01</span><section><strong>Size it.</strong><p>Share the space, dimensions and idea.</p></section></div><div><span>02</span><section><strong>Make it.</strong><p>Agree the artwork and fabrication.</p></section></div><div><span>03</span><section><strong>Fit it.</strong><p>Coordinate the installation.</p></section></div></div><p class="small">Material visualization</p></div></section><section class="section wrap coverage-section"><div class="coverage-layout"><figure class="coverage-image"><img src="${asset('Acc.png')}" alt="Existing ACC roadside signage photograph" loading="lazy"></figure><div><p class="eyebrow">Made here. Seen around here.</p><h2>From city streets<br>to hill roads.</h2><p style="margin-top:22px">Based in Siliguri. Signage and outdoor branding across North Bengal.</p><div class="towns"><span>Siliguri</span><span>Darjeeling</span><span>Jalpaiguri</span><span>Cooch Behar</span><span>Alipurduar</span><span>Kalimpong</span><span>Malda</span><span>The Dooars</span></div><a class="text-link work-link" href="${href('contact')}">Tell us your location <span>↗</span></a></div></div></section>${enquiry()}`}
function servicesPage(){return `<div class="page-heading wrap"><p class="eyebrow">What we make</p><h1>Every surface<br>has potential.</h1><p class="intro">Signage, print and branding, from a single shopfront to a wider rollout.</p></div><img class="service-banner" src="${asset('materials.webp')}" alt="Material visualization of acrylic, vinyl, aluminium and LEDs"><section class="section wrap" style="padding-top:28px"><nav class="category-nav" aria-label="Service groups"><a class="chip" href="#storefront">Storefront</a><a class="chip" href="#campaign">Campaign</a><a class="chip" href="#space">Space & event</a></nav><div class="service-groups">${[['storefront','On your storefront'],['campaign','Out in the world'],['space','Inside your space']].map(([group,t])=>`<section class="service-group" id="${group}"><h2>${t}</h2>${services.map(([name,desc,g],i)=>g===group?`<a class="service-item" href="${href('service')}"><span class="index">${String(i+1).padStart(2,'0')}</span><div><h3>${name}</h3><p>${desc}</p></div><span class="arrow">↗</span></a>`:'').join('')}</section>`).join('')}</div></section>${enquiry()}`}
function servicePage(){return `<div class="detail-top"><div class="page-heading wrap"><p class="eyebrow">Services / Storefront</p><h1>ACP & LED<br>signage.</h1><p class="intro">A clear identity for your storefront.<br>Built to fit the space and your brand.</p>${quote('Discuss this signage')}</div><figure class="service-detail-photo"><img src="${asset('Ambuja_cement_ACP-LED.png')}" alt="Ambuja Cement storefront signage"><figcaption>Ambuja Cement · ACP & LED signage</figcaption></figure></div><section class="detail-intro wrap"><div><h2>A good sign starts<br>with the details.</h2><p class="muted">From the panel finish to the lighting and fixing, we help shape the sign around your site and artwork.</p></div><dl class="details"><div><dt>Materials</dt><dd>ACP · aluminium · LED modules</dd></div><div><dt>Size</dt><dd>Made to your site dimensions</dd></div><div><dt>Planning</dt><dd>Artwork, fabrication & installation</dd></div><div><dt>To get started</dt><dd class="small">Send a site photo, approximate size and location. Confirm material specification, cost and schedule in the quote.</dd></div></dl></section><section class="material-section"><img class="material-visual" src="${asset('materials.webp')}" alt="Material visualization" loading="lazy"><div class="material-copy"><p class="eyebrow">Inside the build</p><h2>A finish worth<br>looking at.</h2><p>Choose the right face material, lighting and fixing for your space. The details should work together.</p><p class="small">Illustrative material study. Final construction is project-specific.</p></div></section><section class="faq wrap"><h2>Before we make it.</h2><details><summary>Can you match our brand colours?</summary><p>Share your brand guidelines and artwork. Colour and material choices are agreed for the project.</p></details><details><summary>What should I send for a quote?</summary><p>A photo of the site, approximate dimensions, your location and any artwork or references.</p></details><details><summary>How is the installation planned?</summary><p>Discuss the site, fixing surface and access with the team when planning your project.</p></details></section>${enquiry()}`}
function workPage(){return `<div class="page-heading wrap"><p class="eyebrow">Our work</p><h1>Out there.<br>Doing its job.</h1><p class="intro">A look at the signs and branding that leave our workshop.</p></div><section class="wrap"><div class="filter-row" aria-label="Filter projects">${[['all','All work'],['signage','Signage'],['vehicles','Vehicles']].map(([v,l],i)=>`<button class="chip work-filter ${i===0?'active':''}" data-value="${v}" aria-pressed="${i===0}">${l}</button>`).join('')}</div><p class="small muted" id="work-count" aria-live="polite" style="margin:0 0 24px">5 projects</p><div class="work-grid">${projects.map(p=>project(p)).join('')}</div></section>${enquiry()}`}
function aboutPage(){return `<div class="page-heading wrap"><p class="eyebrow">About AD-JEET</p><h1>From the workshop.<br>Into the world.</h1><p class="intro">Signage and outdoor branding from Siliguri, since 1990.</p></div><section class="about-grid"><div class="heritage">${logo('heritage-logo')}<p class="eyebrow">An identity with history</p><p class="display">1990</p><p>AD-JEET is an established signage and outdoor-branding business based in Siliguri, serving North Bengal.</p></div><div class="prose wrap"><h2>A practical eye.<br>A maker’s hands.</h2><p>Our work spans fabricated signage, large-format print, vehicle branding, retail spaces and events.</p><p>From an individual storefront to a wider brand rollout, the job is to make your identity visible in the places it needs to be.</p><a class="text-link work-link" href="${href('work')}">See our work <span>↗</span></a><h2>Come with an idea.</h2><p>A site photo, an approximate size, a brand guideline or a rough reference is a useful place to start.</p></div></section><section class="section wrap"><div class="section-head"><h2>The work speaks.</h2></div><div class="proof-secondary">${project(projects[0])}${project(projects[1])}</div></section>${enquiry()}`}
function contactPage(){return `<div class="page-heading wrap"><p class="eyebrow">Start a project</p><h1>Let’s put your<br>name out there.</h1><p class="intro">Start with a photo, a place and an idea.</p></div><div class="contact-grid"><section class="contact-quick">${quote('Start on WhatsApp')}<p>Opens WhatsApp. Attach your site photo there.</p><div class="contact-methods"><a href="#contact-details">Call the team ↗</a><a href="#contact-details">Email us ↗</a></div><div id="contact-details" class="address" style="margin-top:28px"><p class="eyebrow">Talk to us</p><h3>+91 98320 11524</h3><p>ranjitadjeet@gmail.com</p></div><div class="address"><p class="eyebrow">Office</p><h3>Platinum Square</h3><p>Siliguri, West Bengal 734001</p></div><div class="address"><p class="eyebrow">Workshop</p><h3>Patiram Jote</h3><p>Near Siliguri, West Bengal</p></div></section><section class="form-section wrap"><h2>Or leave the details.</h2><p>Fields marked * are required.</p><form id="reference-form"><div class="field"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" placeholder="Full name"></div><div class="field"><label for="phone">Phone number *</label><input id="phone" name="phone" type="tel" autocomplete="tel" placeholder="Your 10-digit mobile number"></div><div class="field"><label for="city">Where is the project? *</label><select id="city"><option value="">Select a city</option>${['Siliguri','Jalpaiguri','Cooch Behar','Darjeeling','Malda','Alipurduar','Kalimpong','Other'].map(c=>`<option>${c}</option>`).join('')}</select></div><div class="field"><fieldset><legend>What do you need? *</legend><div class="check-list">${services.map(([name],i)=>`<label><input type="checkbox" name="services" value="${i}">${name}</label>`).join('')}</div></fieldset></div><div class="field"><label for="timeline">When are you planning it? *</label><select id="timeline"><option>Just exploring</option><option>Immediately</option><option>Within a month</option><option>Within 3 months</option></select></div><div class="field"><label for="message">About the project <span class="optional">(optional)</span></label><textarea id="message" maxlength="1000" placeholder="Approximate size, location or what you have in mind."></textarea></div><div class="form-preview-note">Design preview. The production form retains its existing CAPTCHA and submission service.</div><button class="button" type="submit" style="width:100%">Preview confirmation <span>↗</span></button><p class="small muted" style="margin-top:14px">We use these details to respond to your enquiry.</p><div class="notice" id="form-notice" role="status"><strong>Confirmation state</strong><p>“Your enquiry is in. The team will review your details and get in touch.”</p><p class="small muted" style="margin-top:8px">Preview only. Nothing has been sent or stored.</p></div></form></section></div>`}
function coveragePage(){return `<div class="page-heading wrap"><p class="eyebrow">North Bengal / Siliguri</p><h1>Your storefront.<br>Our home ground.</h1><p class="intro">Signage and outdoor branding in Siliguri, with a workshop nearby at Patiram Jote.</p>${quote('Discuss a Siliguri project')}</div><section class="section wrap" style="padding-top:0">${project(projects[0],'proof-lead')}<p class="small muted" style="margin-top:16px">Work example. Exact installation location is pending verification.</p><div class="prose"><h2>Tell us about the site.</h2><p>Share a photo of the frontage, approximate dimensions, site location and the kind of sign you need.</p><p>The team can discuss materials, artwork, access and installation requirements for your project.</p></div><h2>Choose your service.</h2>${services.slice(0,3).map(([name,desc],i)=>`<a class="service-item" href="${href('service')}"><span class="index">0${i+1}</span><div><h3>${name}</h3><p>${desc}</p></div><span>↗</span></a>`).join('')}</section>${enquiry()}`}
function privacyPage(){return `<article class="legal wrap"><p class="eyebrow muted">Privacy / reading layout</p><h1 style="margin-top:20px">Your details,<br>handled with care.</h1><p>This board specifies typography and spacing for the existing privacy policy. Preserve the approved policy text when implementing.</p><h2>Information you share</h2><p>The full policy content should appear as ordinary readable text in a single column, with clear headings and the existing contact details.</p><h2>A clear way to contact us</h2><p>Keep contact links visible, allow text selection and printing, and avoid overlays that obstruct the policy.</p><a class="text-link" href="${href('contact')}" style="margin-top:24px">Contact AD-JEET ↗</a></article>`}
function directionPage(which){const material=which==='material';return `<section class="direction-hero ${material?'material':'miniature'}"><img src="${asset(material?'materials.webp':'miniature.webp')}" alt="${material?'Sign material concept':'Miniature street concept'}"><span class="scene-caption" style="z-index:3">Exploration · ${material?'B':'C'}</span><div class="direction-copy"><p class="eyebrow">${material?'Craft, brought into focus':'A little world. A lot of visibility.'}</p><h1>${material?'Good signs.<br>Great details.':'A street<br>comes alive.'}</h1><p>Signage, print & outdoor branding.<br>Siliguri. Since 1990.</p>${quote()}</div></section>`}
const renderers={home,services:servicesPage,service:servicePage,work:workPage,about:aboutPage,contact:contactPage,coverage:coveragePage,privacy:privacyPage,material:()=>directionPage('material'),miniature:()=>directionPage('miniature')};
document.getElementById('reference').innerHTML=nav()+`<main>${(renderers[pageName]||home)()}</main>`+footer()+sticky();
if(pageName==='contact'){
 const locations=document.createElement('section');
 locations.className='contact-locations wrap';
 document.querySelectorAll('.contact-quick .address').forEach(address=>locations.append(address));
 document.querySelector('.contact-grid').append(locations);
}
const themeButton=document.getElementById('theme');
function updateThemeButton(){const dark=document.documentElement.dataset.theme==='dark';themeButton.innerHTML=dark?icons.sun:icons.moon;themeButton.setAttribute('aria-label',`Switch to ${dark?'day':'night'} theme`);themeButton.setAttribute('aria-pressed',String(dark));document.querySelectorAll('a[href^="reference.html"]').forEach(a=>{const u=new URL(a.href);u.searchParams.set('theme',dark?'dark':'light');a.href=u.pathname+u.search});}
themeButton.addEventListener('click',()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';updateThemeButton()});
updateThemeButton();
document.getElementById('menu').addEventListener('click',event=>{const menu=document.getElementById('menu-panel');menu.hidden=!menu.hidden;event.currentTarget.setAttribute('aria-expanded',String(!menu.hidden));event.currentTarget.setAttribute('aria-label',menu.hidden?'Open menu':'Close menu')});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){document.getElementById('menu-panel').hidden=true;document.getElementById('menu').setAttribute('aria-expanded','false')}});
function sizeScene(){const plane=document.getElementById('scene-plane');if(!plane)return;const hero=plane.parentElement;const ratio=innerWidth>=1024?1.5:2/3;const w=Math.max(hero.clientWidth,hero.clientHeight*ratio),h=w/ratio;plane.style.width=`${w}px`;plane.style.height=`${h}px`;plane.style.left=`${(hero.clientWidth-w)/2}px`;plane.style.top=`${(hero.clientHeight-h)/2}px`;}
sizeScene();addEventListener('resize',sizeScene);
const dock=document.getElementById('sticky');
addEventListener('scroll',()=>{const hero=document.querySelector('.hero');dock.classList.toggle('visible',pageName!=='contact'&&scrollY>(hero?hero.clientHeight+80:600))},{passive:true});
document.querySelectorAll('.work-filter').forEach(button=>button.addEventListener('click',()=>{const value=button.dataset.value;let count=0;document.querySelectorAll('.work-grid .project').forEach(p=>{p.hidden=value!=='all'&&p.dataset.filter!==value;if(!p.hidden)count++});document.querySelectorAll('.work-filter').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button))});document.getElementById('work-count').textContent=`${count} ${count===1?'project':'projects'}`}));
document.getElementById('reference-form')?.addEventListener('submit',event=>{event.preventDefault();document.getElementById('form-notice').classList.add('visible')});
// WhatsApp controls on the contact artboard demonstrate placement, without sending messages.
if(pageName==='contact')document.querySelector('.contact-quick .button')?.addEventListener('click',event=>{event.preventDefault();document.getElementById('reference-form').scrollIntoView({behavior:'smooth'})});
