import { ServiceSlug } from '@/content/services'
import { CitySlug } from '@/content/cities'

export interface GalleryPhoto {
  id: string
  src: string
  alt: string
  /** The brand on the sign, as named in the client list. */
  client: string
  service: ServiceSlug
  /** Only set when the place is known, so regional pages never claim work that was not there. */
  city?: CitySlug
  /** A place name read from the photo itself (shop address, banner) or the original record. */
  location?: string
  /** Only set when the photo carries a date stamp or the original record gives one. */
  year?: number
  featured: boolean
}

// Every photo is a real site photograph, never generated or AI-retouched.
// Numbers 107 and up come from the updated company profile deck (September
// 2026), with three product displays supplied alongside it; lower numbers are
// the AD-JEET-PROFILE.pptx deck image number. Photos under about 0.25
// megapixels were retired then. City is only set when a GPS stamp or the board
// itself names the city or one of its nearby areas; location and year come from
// the stamp, the board or the deck's file record. The newest work leads the
// list and opens the portfolio: clean frames first, then the photos carrying a
// GPS camera stamp, then the earlier deck's work.
export const photos: GalleryPhoto[] = [
  {
    id: 'acc-125',
    src: '/images/work/acc-acp-125.webp',
    alt: 'ACC ACP fascia lit at night over G.D. and Sons',
    client: 'ACC',
    service: 'acp-led-signage',
    location: 'Dalkhola',
    featured: true,
  },
  {
    id: 'star-cement-137',
    src: '/images/work/star-cement-vehicle-137.webp',
    alt: 'Row of Star RMC transit mixers in red branded livery',
    client: 'Star Cement',
    service: 'vehicle-branding',
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-112',
    src: '/images/work/anchor-by-panasonic-glow-sign-112.webp',
    alt: 'Anchor by Panasonic sign board over Jai Maa Anjani Electricals',
    client: 'Anchor by Panasonic',
    service: 'glow-sign-boards',
    featured: true,
  },
  {
    id: 'havells-116',
    src: '/images/work/havells-display-116.webp',
    alt: 'Havells Stealth Air and BLDC fan display wall with a lit header',
    client: 'Havells',
    service: 'product-display',
    location: 'Maheshtala',
    year: 2024,
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-111',
    src: '/images/work/anchor-by-panasonic-event-111.webp',
    alt: 'Anchor by Panasonic Happy Durga Puja gate framing Dada Bhai Electric',
    client: 'Anchor by Panasonic',
    service: 'events-and-puja',
    location: 'Samaspur',
    featured: true,
  },
  {
    id: 'astral-pipe-129',
    src: '/images/work/astral-pipe-glow-sign-129.webp',
    alt: 'Astral Pipes boards over Punjab Hardware and Electricals in Debidanga, Siliguri',
    client: 'Astral Pipe',
    service: 'glow-sign-boards',
    city: 'siliguri',
    location: 'Debidanga',
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-113',
    src: '/images/work/anchor-by-panasonic-glow-sign-113.webp',
    alt: 'Anchor by Panasonic glow sign lit at night over O.Z. Electricals',
    client: 'Anchor by Panasonic',
    service: 'glow-sign-boards',
    featured: true,
  },
  {
    id: 'srmb-143',
    src: '/images/work/srmb-vehicle-143.webp',
    alt: 'SRMB TMT Wingrip wrap and roof sign on a Maruti Eeco van',
    client: 'SRMB',
    service: 'vehicle-branding',
    featured: true,
  },
  {
    id: 'havells-117',
    src: '/images/work/havells-display-117.webp',
    alt: 'Havells fan, Crabtree switch and water heater display wall under a lit header',
    client: 'Havells',
    service: 'product-display',
    location: 'Dhuliyan',
    year: 2024,
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-114',
    src: '/images/work/anchor-by-panasonic-acp-114.webp',
    alt: 'Anchor by Panasonic ACP fascia over TRG Hardware in Bhutan',
    client: 'Anchor by Panasonic',
    service: 'acp-led-signage',
    location: 'Bhutan',
    featured: true,
  },
  {
    id: 'sd-lion-tmt-139',
    src: '/images/work/sd-lion-tmt-shop-board-139.webp',
    alt: 'SD Lion 600 EQR TMT board over Shibshakti Hardware, photographed at night',
    client: 'SD Lion TMT',
    service: 'flex-printing',
    city: 'cooch-behar',
    location: 'Cooch Behar',
    featured: true,
  },
  {
    id: 'ambuja-cement-126',
    src: '/images/work/ambuja-cement-acp-126.webp',
    alt: 'Ambuja Cement ACP fascia with lit letters over P and P Traders',
    client: 'Ambuja Cement',
    service: 'acp-led-signage',
    location: 'Kushmandi',
    featured: true,
  },
  {
    id: 'acc-128',
    src: '/images/work/acc-f-pole-128.webp',
    alt: 'ACC milestone sign marking Siliguri 26 km on a hill road beside the toy train line',
    client: 'ACC',
    service: 'f-pole-installation',
    location: 'Darjeeling road',
    year: 2025,
    featured: true,
  },
  {
    id: 'supreme-pipe-110',
    src: '/images/work/supreme-pipe-in-shop-110.webp',
    alt: 'Supreme Pipes branded wall behind a pipe and pump display inside a hardware store',
    client: 'Supreme Pipe',
    service: 'in-shop-branding',
    featured: true,
  },
  {
    id: 'havells-120',
    src: '/images/work/havells-display-120.webp',
    alt: 'Havells fan display wall of blades and motor housings under a lit header',
    client: 'Havells',
    service: 'product-display',
    location: 'Maheshtala',
    year: 2024,
    featured: true,
  },
  {
    id: 'astral-pipe-131',
    src: '/images/work/astral-pipe-glow-sign-131.webp',
    alt: 'Astral Pipes boards along the front of the Shyam Iron Udyog showroom',
    client: 'Astral Pipe',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'havells-118',
    src: '/images/work/havells-display-118.webp',
    alt: 'Havells display counter with lit shelves',
    client: 'Havells',
    service: 'product-display',
    featured: false,
  },
  {
    id: 'havells-119',
    src: '/images/work/havells-display-119.webp',
    alt: 'Havells corner display unit with lit shelves',
    client: 'Havells',
    service: 'product-display',
    featured: false,
  },
  {
    id: 'ambuja-cement-123',
    src: '/images/work/ambuja-cement-in-shop-123.webp',
    alt: 'Framed Ambuja Kawach poster on a dealer wall',
    client: 'Ambuja Cement',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'acc-124',
    src: '/images/work/acc-glow-sign-124.webp',
    alt: 'ACC boards over the Prabhat Sarkar shop at Khawakhali Bazar',
    client: 'ACC',
    service: 'glow-sign-boards',
    location: 'Khawakhali',
    year: 2024,
    featured: false,
  },
  {
    id: 'ambuja-cement-127',
    src: '/images/work/ambuja-cement-f-pole-127.webp',
    alt: 'Crew installing an Ambuja Cement milestone sign marking Darjeeling 39 km',
    client: 'Ambuja Cement',
    service: 'f-pole-installation',
    location: 'Darjeeling road',
    year: 2025,
    featured: false,
  },
  {
    id: 'star-cement-136',
    src: '/images/work/star-cement-vehicle-136.webp',
    alt: 'Star RMC branding painted on a transit mixer drum',
    client: 'Star Cement',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'dish-tv-141',
    src: '/images/work/dish-tv-glow-sign-141.webp',
    alt: 'd2h board over Loke Nath Agency',
    client: 'Dish TV',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'dish-tv-142',
    src: '/images/work/dish-tv-in-shop-142.webp',
    alt: 'Dish TV HD wall graphic inside a dealer shop',
    client: 'Dish TV',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-146',
    src: '/images/work/captain-tmt-bar-wall-painting-146.webp',
    alt: 'Captain 600 EQR painted along a tin shop for Roy and Sons Associate',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-147',
    src: '/images/work/captain-tmt-bar-f-pole-147.webp',
    alt: 'Captain 600 EQR pole kiosk for Shree Ram Hardware',
    client: 'Captain TMT Bar',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-148',
    src: '/images/work/captain-tmt-bar-f-pole-148.webp',
    alt: 'Captain 600 EQR pole kiosk mounted high on a street pole',
    client: 'Captain TMT Bar',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-149',
    src: '/images/work/captain-tmt-bar-f-pole-149.webp',
    alt: 'Captain 600 EQR pole kiosk above a busy street corner',
    client: 'Captain TMT Bar',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'supreme-pipe-107',
    src: '/images/work/supreme-pipe-glow-sign-107.webp',
    alt: 'Supreme Pipes and Havells boards over Basanti Hardware Store in Baneswar, Cooch Behar',
    client: 'Supreme Pipe',
    service: 'glow-sign-boards',
    city: 'cooch-behar',
    location: 'Baneswar',
    year: 2025,
    featured: false,
  },
  {
    id: 'supreme-pipe-108',
    src: '/images/work/supreme-pipe-glow-sign-108.webp',
    alt: 'Supreme Pipes glow sign among the brand boards over Nath Paul Hardware and Sanitary',
    client: 'Supreme Pipe',
    service: 'glow-sign-boards',
    location: 'Bakshirhat',
    year: 2025,
    featured: false,
  },
  {
    id: 'supreme-pipe-109',
    src: '/images/work/supreme-pipe-glow-sign-109.webp',
    alt: 'Supreme Pipes glow sign over Sarkar Hardware on a highway market',
    client: 'Supreme Pipe',
    service: 'glow-sign-boards',
    location: 'Maruganj',
    year: 2025,
    featured: false,
  },
  {
    id: 'havells-115',
    src: '/images/work/havells-shop-board-115.webp',
    alt: 'Havells shop board over Jiten Electronics in Gangtok',
    client: 'Havells',
    service: 'flex-printing',
    location: 'Gangtok',
    year: 2025,
    featured: false,
  },
  {
    id: 'ambuja-cement-121',
    src: '/images/work/ambuja-cement-shop-board-121.webp',
    alt: 'Adani Ambuja Cement board over Jyoti Enterprises, photographed at night',
    client: 'Ambuja Cement',
    service: 'flex-printing',
    location: 'Khaprail',
    year: 2025,
    featured: false,
  },
  {
    id: 'ambuja-cement-122',
    src: '/images/work/ambuja-cement-shop-board-122.webp',
    alt: 'Three Adani Ambuja Cement boards along the front of Jyoti Enterprises at night',
    client: 'Ambuja Cement',
    service: 'flex-printing',
    location: 'Khaprail',
    year: 2025,
    featured: false,
  },
  {
    id: 'astral-pipe-130',
    src: '/images/work/astral-pipe-glow-sign-130.webp',
    alt: 'Astral Junction board over Khagrabari Glass House in Cooch Behar',
    client: 'Astral Pipe',
    service: 'glow-sign-boards',
    city: 'cooch-behar',
    location: 'Khagrabari',
    year: 2026,
    featured: false,
  },
  {
    id: 'star-cement-132',
    src: '/images/work/star-cement-event-132.webp',
    alt: 'Star Cement entrance gate at Imran Hardware',
    client: 'Star Cement',
    service: 'events-and-puja',
    location: 'Chakulia',
    year: 2026,
    featured: false,
  },
  {
    id: 'star-cement-133',
    src: '/images/work/star-cement-event-133.webp',
    alt: 'Star Cement entrance gate at Karim Enterprise, photographed at night',
    client: 'Star Cement',
    service: 'events-and-puja',
    location: 'Belshur',
    year: 2026,
    featured: false,
  },
  {
    id: 'star-cement-134',
    src: '/images/work/star-cement-shop-board-134.webp',
    alt: 'Star Cement board over a dealer yard on Siliguri Road, Jalpaiguri',
    client: 'Star Cement',
    service: 'flex-printing',
    city: 'jalpaiguri',
    location: 'Jalpaiguri',
    year: 2025,
    featured: false,
  },
  {
    id: 'star-cement-135',
    src: '/images/work/star-cement-wall-painting-135.webp',
    alt: 'Long Har Ghar Mein Star wall painting for Star Cement',
    client: 'Star Cement',
    service: 'wall-painting',
    location: 'Buniadpur',
    year: 2025,
    featured: false,
  },
  {
    id: 'sd-lion-tmt-138',
    src: '/images/work/sd-lion-tmt-shop-board-138.webp',
    alt: 'SD Lion 600 EQR TMT board over Jhilon Enterprise in Ghughudanga, Jalpaiguri',
    client: 'SD Lion TMT',
    service: 'flex-printing',
    city: 'jalpaiguri',
    location: 'Ghughudanga',
    year: 2025,
    featured: false,
  },
  {
    id: 'sd-lion-tmt-140',
    src: '/images/work/sd-lion-tmt-wall-painting-140.webp',
    alt: 'SD Lion TMT wall painting for Bengal Hardware Stores in Dinhata',
    client: 'SD Lion TMT',
    service: 'wall-painting',
    city: 'cooch-behar',
    location: 'Dinhata',
    year: 2025,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-144',
    src: '/images/work/captain-tmt-bar-shop-board-144.webp',
    alt: 'Captain 600 EQR board over Routh Hardware in Jiranpur, Cooch Behar',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    city: 'cooch-behar',
    location: 'Jiranpur',
    year: 2023,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-145',
    src: '/images/work/captain-tmt-bar-shop-board-145.webp',
    alt: 'Captain 600 EQR board over Subhankar Enterprise in Ghughumari, Cooch Behar',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    city: 'cooch-behar',
    location: 'Ghughumari',
    year: 2023,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-150',
    src: '/images/work/captain-tmt-bar-shop-board-150.webp',
    alt: 'Captain 600 EQR boards over Bhai Bhai Hardware in Cooch Behar',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    city: 'cooch-behar',
    location: 'Cooch Behar',
    year: 2025,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-151',
    src: '/images/work/captain-tmt-bar-shop-board-151.webp',
    alt: 'Captain 600 EQR board on a roadside wall for Chandamari Hardware, Cooch Behar',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    city: 'cooch-behar',
    location: 'Chandamari',
    year: 2025,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-152',
    src: '/images/work/captain-tmt-bar-in-shop-152.webp',
    alt: 'Captain 600 EQR graphics on the glass doors of a dealer cabin',
    client: 'Captain TMT Bar',
    service: 'in-shop-branding',
    location: 'Mandalghat',
    year: 2025,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-153',
    src: '/images/work/captain-tmt-bar-shop-board-153.webp',
    alt: 'Captain 600 EQR boards over R N R Hardware',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    location: 'Sannyasikata',
    year: 2025,
    featured: false,
  },
  {
    id: 'acc-102',
    src: '/images/work/acc-shop-board-102.webp',
    alt: 'ACC and Asian Paints boards wrapped around a corner store',
    client: 'ACC',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'havells-015',
    src: '/images/work/havells-glow-sign-015.webp',
    alt: 'Standard by Havells illuminated sign board at night on Agrasen Road, Jalpaiguri',
    client: 'Havells',
    service: 'glow-sign-boards',
    city: 'jalpaiguri',
    location: 'Jalpaiguri',
    year: 2021,
    featured: true,
  },
  {
    id: 'captain-tmt-bar-078',
    src: '/images/work/captain-tmt-bar-wall-painting-078.webp',
    alt: 'Captain 600 EQR wall painting framing a hardware store entrance',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'toptech-tmt-047',
    src: '/images/work/toptech-tmt-vehicle-047.webp',
    alt: 'Toptech TMT side wrap on a red SUV at night',
    client: 'Toptech TMT',
    service: 'vehicle-branding',
    featured: true,
  },
  {
    id: 'toptech-tmt-040',
    src: '/images/work/toptech-tmt-in-shop-040.webp',
    alt: 'Toptech TMT wall graphics and standees inside a dealer showroom',
    client: 'Toptech TMT',
    service: 'in-shop-branding',
    featured: true,
  },
  {
    id: 'supreme-pipe-085',
    src: '/images/work/supreme-pipe-event-085.webp',
    alt: 'Supreme Durga Puja entrance gate',
    client: 'Supreme Pipe',
    service: 'events-and-puja',
    featured: true,
  },
  {
    id: 'supreme-pipe-064',
    src: '/images/work/supreme-pipe-acp-064.webp',
    alt: 'Raised Bengali letters and a Supreme sign on a hardware store facade in Raiganj',
    client: 'Supreme Pipe',
    service: 'acp-led-signage',
    location: 'Raiganj',
    featured: true,
  },
  {
    id: 'sel-tmt-058',
    src: '/images/work/sel-tmt-wall-painting-058.webp',
    alt: 'SEL Tiger TMT wall painting on a corrugated fence',
    client: 'SEL TMT',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'toptech-tmt-044',
    src: '/images/work/toptech-tmt-wall-painting-044.webp',
    alt: 'Toptech TMT Bengali wall painting on a boundary wall',
    client: 'Toptech TMT',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'captain-tmt-bar-072',
    src: '/images/work/captain-tmt-bar-shop-board-072.webp',
    alt: 'Captain, Shyam Steel and dealer boards over a hardware store',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-106',
    src: '/images/work/anchor-by-panasonic-glow-sign-106.webp',
    alt: 'Anchor by Panasonic illuminated sign board at night',
    client: 'Anchor by Panasonic',
    service: 'glow-sign-boards',
    featured: true,
  },
  {
    id: 'airtel-008',
    src: '/images/work/airtel-wall-painting-008.webp',
    alt: 'Airtel wall painting with a Bengali network message',
    client: 'Airtel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'star-cement-022',
    src: '/images/work/star-cement-shop-board-022.webp',
    alt: 'Star Cement shop board over a village store',
    client: 'Star Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'star-cement-023',
    src: '/images/work/star-cement-shop-board-023.webp',
    alt: 'Star Cement dealer board with raised letters',
    client: 'Star Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'toptech-tmt-041',
    src: '/images/work/toptech-tmt-shop-board-041.webp',
    alt: 'Toptech TMT shop board over a cement agency',
    client: 'Toptech TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'toptech-tmt-042',
    src: '/images/work/toptech-tmt-shop-board-042.webp',
    alt: 'Toptech TMT board over a painted village hardware store',
    client: 'Toptech TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'toptech-tmt-043',
    src: '/images/work/toptech-tmt-in-shop-043.webp',
    alt: 'Toptech TMT wall panel inside a dealer office',
    client: 'Toptech TMT',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'toptech-tmt-045',
    src: '/images/work/toptech-tmt-wall-painting-045.webp',
    alt: 'Toptech TMT artwork painted on shop shutters',
    client: 'Toptech TMT',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'sel-tmt-054',
    src: '/images/work/sel-tmt-shop-board-054.webp',
    alt: 'SEL Tiger TMT board on top of a hardware store',
    client: 'SEL TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'sel-tmt-055',
    src: '/images/work/sel-tmt-f-pole-055.webp',
    alt: 'SEL Tiger TMT F-pole sign beside a shop',
    client: 'SEL TMT',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'sel-tmt-056',
    src: '/images/work/sel-tmt-f-pole-056.webp',
    alt: 'SEL Tiger TMT F-pole sign on a village road',
    client: 'SEL TMT',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'sel-tmt-057',
    src: '/images/work/sel-tmt-shop-board-057.webp',
    alt: 'SEL Tiger TMT shop board with Dalmia Cement branding, at night',
    client: 'SEL TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'sel-tmt-059',
    src: '/images/work/sel-tmt-wall-painting-059.webp',
    alt: 'SEL Tiger TMT wall painting under a covered walkway',
    client: 'SEL TMT',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-067',
    src: '/images/work/supreme-pipe-shop-board-067.webp',
    alt: 'Supreme shop board over Everest Enterprise',
    client: 'Supreme Pipe',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'supreme-pipe-068',
    src: '/images/work/supreme-pipe-wall-painting-068.webp',
    alt: 'Supreme wall painting beside a highway',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-069',
    src: '/images/work/supreme-pipe-wall-painting-069.webp',
    alt: 'Supreme wall painting covering the front of Himalayan Stores',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-070',
    src: '/images/work/supreme-pipe-wall-painting-070.webp',
    alt: 'Supreme artwork painted on a shop shutter',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-071',
    src: '/images/work/supreme-pipe-wall-painting-071.webp',
    alt: 'Supreme branding painted on a gate',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-073',
    src: '/images/work/captain-tmt-bar-shop-board-073.webp',
    alt: 'Captain TMT shop boards over a village hardware store',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-074',
    src: '/images/work/captain-tmt-bar-shop-board-074.webp',
    alt: 'Captain TMT shop boards along a market row',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-075',
    src: '/images/work/captain-tmt-bar-shop-board-075.webp',
    alt: 'Captain TMT hoarding at night',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    year: 2021,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-076',
    src: '/images/work/captain-tmt-bar-wall-painting-076.webp',
    alt: 'Captain 600 EQR wall painting on a warehouse',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-077',
    src: '/images/work/captain-tmt-bar-wall-painting-077.webp',
    alt: 'Captain 600 EQR painted on a tin shop',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-079',
    src: '/images/work/captain-tmt-bar-wall-painting-079.webp',
    alt: 'Captain 600 EQR wall painting on a roadside building',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-082',
    src: '/images/work/supreme-pipe-event-082.webp',
    alt: 'Supreme branded entrance gate at a hardware store',
    client: 'Supreme Pipe',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'lloyd-084',
    src: '/images/work/lloyd-event-084.webp',
    alt: 'Lloyd puja season display kiosk on a market street',
    client: 'Lloyd',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'emami-089',
    src: '/images/work/emami-shop-board-089.webp',
    alt: 'Emami Healthy and Tasty board over a busy grocery store',
    client: 'Emami',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'acc-103',
    src: '/images/work/acc-shop-board-103.webp',
    alt: 'ACC shop board over a hardware store',
    client: 'ACC',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'acc-104',
    src: '/images/work/acc-wall-painting-104.webp',
    alt: 'ACC wall painting for Ganesh Enterprise beside a road',
    client: 'ACC',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'acc-105',
    src: '/images/work/acc-wall-painting-105.webp',
    alt: 'Long ACC wall painting for Ganesh Enterprise',
    client: 'ACC',
    service: 'wall-painting',
    featured: false,
  },
]

/** Hand-picked lead photo for each service page, chosen for resolution and clarity. */
const SERVICE_COVERS: Partial<Record<ServiceSlug, string>> = {
  'glow-sign-boards': 'havells-015',
  'acp-led-signage': 'acc-125',
  'flex-printing': 'captain-tmt-bar-072',
  'vehicle-branding': 'srmb-143',
  'wall-painting': 'sel-tmt-058',
  'f-pole-installation': 'captain-tmt-bar-148',
  'in-shop-branding': 'supreme-pipe-110',
  'events-and-puja': 'supreme-pipe-085',
  'product-display': 'havells-116',
}

export function clientSlug(client: string): string {
  return client.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export function getPhotoById(id: string): GalleryPhoto {
  const photo = photos.find(p => p.id === id)
  if (!photo) throw new Error(`Missing gallery photo: ${id}`)
  return photo
}

export function getFeaturedPhotos(): GalleryPhoto[] {
  return photos.filter(p => p.featured)
}

export function getPhotosByService(service: ServiceSlug): GalleryPhoto[] {
  return photos.filter(p => p.service === service)
}

export function getPhotosByCity(city: CitySlug): GalleryPhoto[] {
  return photos.filter(p => p.city === city)
}

export function getPhotosByClient(slug: string): GalleryPhoto[] {
  return photos.filter(p => clientSlug(p.client) === slug)
}

export function getServiceCover(service: ServiceSlug): GalleryPhoto | undefined {
  const id = SERVICE_COVERS[service]
  return (id && photos.find(p => p.id === id)) || photos.find(p => p.service === service)
}

/** Brands with at least one photo, most photographed first. */
export function getClients(): { slug: string; name: string; count: number }[] {
  const counts = new Map<string, { slug: string; name: string; count: number }>()
  for (const p of photos) {
    const slug = clientSlug(p.client)
    const current = counts.get(slug) ?? { slug, name: p.client, count: 0 }
    current.count += 1
    counts.set(slug, current)
  }
  return [...counts.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
}
