import { ServiceSlug } from '@/content/services'
import { CitySlug } from '@/content/cities'

export interface GalleryPhoto {
  id: string
  src: string
  alt: string
  /** The brand on the sign, as named in the client list. */
  client: string
  service: ServiceSlug
  /** Only set when the place is known, so regional pages never claim work that was not there. */
  city?: CitySlug
  /** A place name read from the photo itself (shop address, banner) or the original record. */
  location?: string
  /** Only set when the photo carries a date stamp or the original record gives one. */
  year?: number
  featured: boolean
}

// The first five entries were published before the company profile deck was
// imported. Everything under /images/work comes from AD-JEET-PROFILE.pptx
// (deck image number in the file name). Places and years are only filled in
// where the photo itself shows them.
export const photos: GalleryPhoto[] = [
  {
    id: 'acc-102',
    src: '/images/work/acc-shop-board-102.webp',
    alt: 'ACC and Asian Paints boards wrapped around a corner store',
    client: 'ACC',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'havells-015',
    src: '/images/work/havells-glow-sign-015.webp',
    alt: 'Standard by Havells illuminated sign board at night on Agrasen Road, Jalpaiguri',
    client: 'Havells',
    service: 'glow-sign-boards',
    city: 'jalpaiguri',
    location: 'Jalpaiguri',
    year: 2021,
    featured: true,
  },
  {
    id: 'captain-tmt-bar-078',
    src: '/images/work/captain-tmt-bar-wall-painting-078.webp',
    alt: 'Captain 600 EQR wall painting framing a hardware store entrance',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'toptech-tmt-047',
    src: '/images/work/toptech-tmt-vehicle-047.webp',
    alt: 'Toptech TMT side wrap on a red SUV at night',
    client: 'Toptech TMT',
    service: 'vehicle-branding',
    featured: true,
  },
  {
    id: 'star-cement-026',
    src: '/images/work/star-cement-wall-painting-026.webp',
    alt: 'Star Cement artwork painted on the shutters of Bansal Traders, Matigara',
    client: 'Star Cement',
    service: 'wall-painting',
    city: 'siliguri',
    location: 'Matigara',
    featured: true,
  },
  {
    id: 'toptech-tmt-040',
    src: '/images/work/toptech-tmt-in-shop-040.webp',
    alt: 'Toptech TMT wall graphics and standees inside a dealer showroom',
    client: 'Toptech TMT',
    service: 'in-shop-branding',
    featured: true,
  },
  {
    id: 'supreme-pipe-085',
    src: '/images/work/supreme-pipe-event-085.webp',
    alt: 'Supreme Durga Puja entrance gate',
    client: 'Supreme Pipe',
    service: 'events-and-puja',
    featured: true,
  },
  {
    id: 'supreme-pipe-064',
    src: '/images/work/supreme-pipe-acp-064.webp',
    alt: 'Raised Bengali letters and a Supreme sign on a hardware store facade in Raiganj',
    client: 'Supreme Pipe',
    service: 'acp-led-signage',
    location: 'Raiganj',
    featured: true,
  },
  {
    id: 'sel-tmt-058',
    src: '/images/work/sel-tmt-wall-painting-058.webp',
    alt: 'SEL Tiger TMT wall painting on a corrugated fence',
    client: 'SEL TMT',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'star-cement-030',
    src: '/images/work/star-cement-vehicle-030.webp',
    alt: 'Star Cement branded delivery truck',
    client: 'Star Cement',
    service: 'vehicle-branding',
    featured: true,
  },
  {
    id: 'oyo-090',
    src: '/images/work/oyo-glow-sign-090.webp',
    alt: 'OYO Rooms glow sign on a hotel wall at night',
    client: 'OYO',
    service: 'glow-sign-boards',
    featured: true,
  },
  {
    id: 'toptech-tmt-049',
    src: '/images/work/toptech-tmt-event-049.webp',
    alt: 'Toptech TMT stage backdrop and standees in a banquet hall',
    client: 'Toptech TMT',
    service: 'events-and-puja',
    featured: true,
  },
  {
    id: 'toptech-tmt-044',
    src: '/images/work/toptech-tmt-wall-painting-044.webp',
    alt: 'Toptech TMT Bengali wall painting on a boundary wall',
    client: 'Toptech TMT',
    service: 'wall-painting',
    featured: true,
  },
  {
    id: 'captain-tmt-bar-072',
    src: '/images/work/captain-tmt-bar-shop-board-072.webp',
    alt: 'Captain, Shyam Steel and dealer boards over a hardware store',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: true,
  },
  {
    id: 'havells-020',
    src: '/images/work/havells-display-020.webp',
    alt: 'Havells Reo switch display wall in an electrical store',
    client: 'Havells',
    service: 'product-display',
    featured: true,
  },
  {
    id: 'anchor-by-panasonic-106',
    src: '/images/work/anchor-by-panasonic-glow-sign-106.webp',
    alt: 'Anchor by Panasonic illuminated sign board at night',
    client: 'Anchor by Panasonic',
    service: 'glow-sign-boards',
    featured: true,
  },
  {
    id: 'gs-acc',
    src: '/Acc.png',
    alt: 'Glow sign board for ACC Cement installed by AD JEET',
    client: 'ACC',
    service: 'glow-sign-boards',
    city: 'siliguri',
    location: 'Siliguri',
    year: 2024,
    featured: true,
  },
  {
    id: 'acp-ambuja',
    src: '/Ambuja_cement_ACP-LED.png',
    alt: 'ACP and LED signage for Ambuja Cement fabricated by AD JEET',
    client: 'Ambuja Cement',
    service: 'acp-led-signage',
    city: 'jalpaiguri',
    location: 'Jalpaiguri',
    year: 2024,
    featured: true,
  },
  {
    id: 'gs-gates',
    src: '/Gates.png',
    alt: 'Anchor by Panasonic branded entrance for Durga Puja by AD JEET',
    client: 'Anchor by Panasonic',
    service: 'events-and-puja',
    city: 'darjeeling',
    location: 'Darjeeling',
    year: 2023,
    featured: true,
  },
  {
    id: 'vb-srmb',
    src: '/SRMB_vechile.png',
    alt: 'SRMB vehicle branding wrap on a delivery truck by AD JEET',
    client: 'SRMB',
    service: 'vehicle-branding',
    city: 'malda',
    location: 'Malda',
    year: 2024,
    featured: true,
  },
  {
    id: 'gs-airtel',
    src: '/airtel.png',
    alt: 'Airtel wall advertising painted by AD JEET',
    client: 'Airtel',
    service: 'wall-painting',
    city: 'cooch-behar',
    location: 'Cooch Behar',
    year: 2024,
    featured: true,
  },
  {
    id: 'airtel-003',
    src: '/images/work/airtel-shop-board-003.webp',
    alt: 'Airtel shop fascia board above a two-storey storefront',
    client: 'Airtel',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'airtel-004',
    src: '/images/work/airtel-glow-sign-004.webp',
    alt: 'Airtel myATM flange sign mounted on a shop canopy',
    client: 'Airtel',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'airtel-005',
    src: '/images/work/airtel-f-pole-005.webp',
    alt: 'Airtel F-pole sign beside a roadside shop',
    client: 'Airtel',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'airtel-006',
    src: '/images/work/airtel-shop-board-006.webp',
    alt: 'Airtel retailer board with branded glass door panels',
    client: 'Airtel',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'airtel-007',
    src: '/images/work/airtel-wall-painting-007.webp',
    alt: 'Airtel artwork painted across two shop shutters',
    client: 'Airtel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'airtel-008',
    src: '/images/work/airtel-wall-painting-008.webp',
    alt: 'Airtel wall painting with a Bengali network message',
    client: 'Airtel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'airtel-009',
    src: '/images/work/airtel-wall-painting-009.webp',
    alt: 'Long Airtel wall painting along a paddy field',
    client: 'Airtel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'airtel-010',
    src: '/images/work/airtel-shop-board-010.webp',
    alt: 'Airtel recharge shop board with branded pillar panels',
    client: 'Airtel',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'airtel-011',
    src: '/images/work/airtel-f-pole-011.webp',
    alt: 'Airtel Payments Bank F-pole sign on a rural road',
    client: 'Airtel',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'airtel-012',
    src: '/images/work/airtel-in-shop-012.webp',
    alt: 'Framed Airtel DTH poster inside a retail store',
    client: 'Airtel',
    service: 'in-shop-branding',
    year: 2021,
    featured: false,
  },
  {
    id: 'airtel-013',
    src: '/images/work/airtel-in-shop-013.webp',
    alt: 'Framed Airtel posters on a store wall',
    client: 'Airtel',
    service: 'in-shop-branding',
    year: 2021,
    featured: false,
  },
  {
    id: 'havells-014',
    src: '/images/work/havells-in-shop-014.webp',
    alt: 'Havells fan and water heater wall graphics inside a showroom',
    client: 'Havells',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'havells-016',
    src: '/images/work/havells-glow-sign-016.webp',
    alt: 'Havells illuminated shop sign at night',
    client: 'Havells',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'havells-017',
    src: '/images/work/havells-shop-board-017.webp',
    alt: 'Havells Electric Point shop board with Bengali lettering',
    client: 'Havells',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'havells-018',
    src: '/images/work/havells-display-018.webp',
    alt: 'Havells switch and lighting display panels',
    client: 'Havells',
    service: 'product-display',
    featured: false,
  },
  {
    id: 'havells-019',
    src: '/images/work/havells-display-019.webp',
    alt: 'Illuminated Havells kitchen appliance display',
    client: 'Havells',
    service: 'product-display',
    featured: false,
  },
  {
    id: 'havells-021',
    src: '/images/work/havells-display-021.webp',
    alt: 'Havells switch display boards in a shop, with the shopkeepers at the counter',
    client: 'Havells',
    service: 'product-display',
    featured: false,
  },
  {
    id: 'star-cement-022',
    src: '/images/work/star-cement-shop-board-022.webp',
    alt: 'Star Cement shop board over a village store',
    client: 'Star Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'star-cement-023',
    src: '/images/work/star-cement-shop-board-023.webp',
    alt: 'Star Cement dealer board with raised letters',
    client: 'Star Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'star-cement-024',
    src: '/images/work/star-cement-shop-board-024.webp',
    alt: 'Star Cement shop board and projecting sign on a highway market',
    client: 'Star Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'star-cement-025',
    src: '/images/work/star-cement-in-shop-025.webp',
    alt: 'Star Cement branding panel inside a hardware store',
    client: 'Star Cement',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'star-cement-027',
    src: '/images/work/star-cement-wall-painting-027.webp',
    alt: 'Star Cement and Anti Rust wall painting beside a road',
    client: 'Star Cement',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'star-cement-028',
    src: '/images/work/star-cement-wall-painting-028.webp',
    alt: 'Star Anti Rust wall painting on a concrete wall',
    client: 'Star Cement',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'star-cement-029',
    src: '/images/work/star-cement-wall-painting-029.webp',
    alt: 'Star Cement dealer wall painting for Paul and Co.',
    client: 'Star Cement',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'star-cement-031',
    src: '/images/work/star-cement-vehicle-031.webp',
    alt: 'Star Cement Dhalai Mein Must graphics on a delivery van',
    client: 'Star Cement',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'srmb-032',
    src: '/images/work/srmb-shop-board-032.webp',
    alt: 'SRMB TMT hoarding on a roadside frame',
    client: 'SRMB',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'srmb-033',
    src: '/images/work/srmb-shop-board-033.webp',
    alt: 'SRMB TMT hoarding and shop boards over a hardware store',
    client: 'SRMB',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'srmb-034',
    src: '/images/work/srmb-wall-painting-034.webp',
    alt: 'SRMB TMT Wingrip wall painting for Deb Hardware',
    client: 'SRMB',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'srmb-035',
    src: '/images/work/srmb-wall-painting-035.webp',
    alt: 'SRMB TMT wall painting for a dealer in Paharpur, Jalpaiguri',
    client: 'SRMB',
    service: 'wall-painting',
    city: 'jalpaiguri',
    location: 'Paharpur, Jalpaiguri',
    featured: false,
  },
  {
    id: 'srmb-036',
    src: '/images/work/srmb-vehicle-036.webp',
    alt: 'SRMB Real Edge car wrap photographed at night',
    client: 'SRMB',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'srmb-037',
    src: '/images/work/srmb-vehicle-037.webp',
    alt: 'Yellow SRMB branded car, front view at night',
    client: 'SRMB',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'srmb-038',
    src: '/images/work/srmb-vehicle-038.webp',
    alt: 'Yellow SRMB branded car, rear view at night',
    client: 'SRMB',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'srmb-039',
    src: '/images/work/srmb-vehicle-039.webp',
    alt: 'SRMB TMT Wingrip car wrap, side view at night',
    client: 'SRMB',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'toptech-tmt-041',
    src: '/images/work/toptech-tmt-shop-board-041.webp',
    alt: 'Toptech TMT shop board over a cement agency',
    client: 'Toptech TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'toptech-tmt-042',
    src: '/images/work/toptech-tmt-shop-board-042.webp',
    alt: 'Toptech TMT board over a painted village hardware store',
    client: 'Toptech TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'toptech-tmt-043',
    src: '/images/work/toptech-tmt-in-shop-043.webp',
    alt: 'Toptech TMT wall panel inside a dealer office',
    client: 'Toptech TMT',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'toptech-tmt-045',
    src: '/images/work/toptech-tmt-wall-painting-045.webp',
    alt: 'Toptech TMT artwork painted on shop shutters',
    client: 'Toptech TMT',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'toptech-tmt-046',
    src: '/images/work/toptech-tmt-vehicle-046.webp',
    alt: 'Toptech TMT wrap on a red car at night',
    client: 'Toptech TMT',
    service: 'vehicle-branding',
    featured: false,
  },
  {
    id: 'toptech-tmt-048',
    src: '/images/work/toptech-tmt-event-048.webp',
    alt: 'Toptech TMT roll-up standee at a dealer event',
    client: 'Toptech TMT',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'shyam-steel-050',
    src: '/images/work/shyam-steel-in-shop-050.webp',
    alt: 'Shyam Steel poster panel inside a store',
    client: 'Shyam Steel',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'shyam-steel-051',
    src: '/images/work/shyam-steel-shop-board-051.webp',
    alt: 'Shyam Steel shop boards along a roadside market',
    client: 'Shyam Steel',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'shyam-steel-052',
    src: '/images/work/shyam-steel-shop-board-052.webp',
    alt: 'Shyam Steel and Captain shop boards over hardware stores',
    client: 'Shyam Steel',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'shyam-steel-053',
    src: '/images/work/shyam-steel-in-shop-053.webp',
    alt: 'Shyam Steel wall branding inside a store',
    client: 'Shyam Steel',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'sel-tmt-054',
    src: '/images/work/sel-tmt-shop-board-054.webp',
    alt: 'SEL Tiger TMT board on top of a hardware store',
    client: 'SEL TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'sel-tmt-055',
    src: '/images/work/sel-tmt-f-pole-055.webp',
    alt: 'SEL Tiger TMT F-pole sign beside a shop',
    client: 'SEL TMT',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'sel-tmt-056',
    src: '/images/work/sel-tmt-f-pole-056.webp',
    alt: 'SEL Tiger TMT F-pole sign on a village road',
    client: 'SEL TMT',
    service: 'f-pole-installation',
    featured: false,
  },
  {
    id: 'sel-tmt-057',
    src: '/images/work/sel-tmt-shop-board-057.webp',
    alt: 'SEL Tiger TMT shop board with Dalmia Cement branding, at night',
    client: 'SEL TMT',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'sel-tmt-059',
    src: '/images/work/sel-tmt-wall-painting-059.webp',
    alt: 'SEL Tiger TMT wall painting under a covered walkway',
    client: 'SEL TMT',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'shyam-steel-060',
    src: '/images/work/shyam-steel-wall-painting-060.webp',
    alt: 'Shyam Steel painted wall with hoardings above',
    client: 'Shyam Steel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'shyam-steel-061',
    src: '/images/work/shyam-steel-wall-painting-061.webp',
    alt: 'Shyam Steel dealer wall painting beside a road',
    client: 'Shyam Steel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'shyam-steel-062',
    src: '/images/work/shyam-steel-wall-painting-062.webp',
    alt: 'Shyam Steel artwork painted on a shop shutter',
    client: 'Shyam Steel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'shyam-steel-063',
    src: '/images/work/shyam-steel-wall-painting-063.webp',
    alt: 'Shyam Steel wall painting for Jyoti Enterprises',
    client: 'Shyam Steel',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-065',
    src: '/images/work/supreme-pipe-in-shop-065.webp',
    alt: 'Supreme Pipes counter panel inside a shop',
    client: 'Supreme Pipe',
    service: 'in-shop-branding',
    featured: false,
  },
  {
    id: 'supreme-pipe-066',
    src: '/images/work/supreme-pipe-shop-board-066.webp',
    alt: 'Supreme shop board and projecting signs',
    client: 'Supreme Pipe',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'supreme-pipe-067',
    src: '/images/work/supreme-pipe-shop-board-067.webp',
    alt: 'Supreme shop board over Everest Enterprise',
    client: 'Supreme Pipe',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'supreme-pipe-068',
    src: '/images/work/supreme-pipe-wall-painting-068.webp',
    alt: 'Supreme wall painting beside a highway',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-069',
    src: '/images/work/supreme-pipe-wall-painting-069.webp',
    alt: 'Supreme wall painting covering the front of Himalayan Stores',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-070',
    src: '/images/work/supreme-pipe-wall-painting-070.webp',
    alt: 'Supreme artwork painted on a shop shutter',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'supreme-pipe-071',
    src: '/images/work/supreme-pipe-wall-painting-071.webp',
    alt: 'Supreme branding painted on a gate',
    client: 'Supreme Pipe',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-073',
    src: '/images/work/captain-tmt-bar-shop-board-073.webp',
    alt: 'Captain TMT shop boards over a village hardware store',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-074',
    src: '/images/work/captain-tmt-bar-shop-board-074.webp',
    alt: 'Captain TMT shop boards along a market row',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-075',
    src: '/images/work/captain-tmt-bar-shop-board-075.webp',
    alt: 'Captain TMT hoarding at night',
    client: 'Captain TMT Bar',
    service: 'flex-printing',
    year: 2021,
    featured: false,
  },
  {
    id: 'captain-tmt-bar-076',
    src: '/images/work/captain-tmt-bar-wall-painting-076.webp',
    alt: 'Captain 600 EQR wall painting on a warehouse',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-077',
    src: '/images/work/captain-tmt-bar-wall-painting-077.webp',
    alt: 'Captain 600 EQR painted on a tin shop',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'captain-tmt-bar-079',
    src: '/images/work/captain-tmt-bar-wall-painting-079.webp',
    alt: 'Captain 600 EQR wall painting on a roadside building',
    client: 'Captain TMT Bar',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'dish-tv-080',
    src: '/images/work/dish-tv-event-080.webp',
    alt: 'Dish TV puja season shopfront branding with a d2h standee',
    client: 'Dish TV',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'astral-pipe-081',
    src: '/images/work/astral-pipe-event-081.webp',
    alt: 'Astral Pipes branded entrance gate for the puja season',
    client: 'Astral Pipe',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'supreme-pipe-082',
    src: '/images/work/supreme-pipe-event-082.webp',
    alt: 'Supreme branded entrance gate at a hardware store',
    client: 'Supreme Pipe',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'lloyd-083',
    src: '/images/work/lloyd-event-083.webp',
    alt: 'Lloyd Great Pujo Festive Bonanza gate at a shop in Bagdogra',
    client: 'Lloyd',
    service: 'events-and-puja',
    location: 'Bagdogra',
    featured: false,
  },
  {
    id: 'lloyd-084',
    src: '/images/work/lloyd-event-084.webp',
    alt: 'Lloyd puja season display kiosk on a market street',
    client: 'Lloyd',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'emami-086',
    src: '/images/work/emami-shop-board-086.webp',
    alt: 'Emami Mantra Masala board and pillar panels at a grocery store',
    client: 'Emami',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'emami-087',
    src: '/images/work/emami-shop-board-087.webp',
    alt: 'Emami Mantra Masala shop board over Purbasha Store',
    client: 'Emami',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'emami-088',
    src: '/images/work/emami-shop-board-088.webp',
    alt: 'Emami Mantra Masala shop board over a market stall',
    client: 'Emami',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'emami-089',
    src: '/images/work/emami-shop-board-089.webp',
    alt: 'Emami Healthy and Tasty board over a busy grocery store',
    client: 'Emami',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'oyo-091',
    src: '/images/work/oyo-glow-sign-091.webp',
    alt: 'OYO projecting glow sign on a hill town building',
    client: 'OYO',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'oyo-092',
    src: '/images/work/oyo-glow-sign-092.webp',
    alt: 'OYO sign board at a hotel entrance',
    client: 'OYO',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'oyo-093',
    src: '/images/work/oyo-glow-sign-093.webp',
    alt: 'OYO sign on a hotel balcony',
    client: 'OYO',
    service: 'glow-sign-boards',
    featured: false,
  },
  {
    id: 'shyam-steel-094',
    src: '/images/work/shyam-steel-event-094.webp',
    alt: 'Shyam Steel standees and banner at a general meeting in Dhupguri',
    client: 'Shyam Steel',
    service: 'events-and-puja',
    location: 'Dhupguri',
    year: 2019,
    featured: false,
  },
  {
    id: 'havells-095',
    src: '/images/work/havells-event-095.webp',
    alt: 'Havells delegate welcome stall',
    client: 'Havells',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'havells-096',
    src: '/images/work/havells-event-096.webp',
    alt: 'Havells Welcome to All Delegates stage backdrop',
    client: 'Havells',
    service: 'events-and-puja',
    featured: false,
  },
  {
    id: 'dalmia-cement-097',
    src: '/images/work/dalmia-cement-shop-board-097.webp',
    alt: 'Dalmia Cement gate and shop boards over a hardware store',
    client: 'Dalmia Cement',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'dalmia-cement-098',
    src: '/images/work/dalmia-cement-wall-painting-098.webp',
    alt: 'Dalmia Cement wall painting for Munna Hardware',
    client: 'Dalmia Cement',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'jio-099',
    src: '/images/work/jio-shop-board-099.webp',
    alt: 'Jio Digital Life shop board over a mobile store',
    client: 'Jio',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'vivo-100',
    src: '/images/work/vivo-acp-100.webp',
    alt: 'Vivo Gift Centre ACP storefront',
    client: 'Vivo',
    service: 'acp-led-signage',
    featured: false,
  },
  {
    id: 'vivo-101',
    src: '/images/work/vivo-acp-101.webp',
    alt: 'Vivo ACP facade for a mobile phone store',
    client: 'Vivo',
    service: 'acp-led-signage',
    featured: false,
  },
  {
    id: 'acc-103',
    src: '/images/work/acc-shop-board-103.webp',
    alt: 'ACC shop board over a hardware store',
    client: 'ACC',
    service: 'flex-printing',
    featured: false,
  },
  {
    id: 'acc-104',
    src: '/images/work/acc-wall-painting-104.webp',
    alt: 'ACC wall painting for Ganesh Enterprise beside a road',
    client: 'ACC',
    service: 'wall-painting',
    featured: false,
  },
  {
    id: 'acc-105',
    src: '/images/work/acc-wall-painting-105.webp',
    alt: 'Long ACC wall painting for Ganesh Enterprise',
    client: 'ACC',
    service: 'wall-painting',
    featured: false,
  },
]

/** Hand-picked lead photo for each service page, chosen for resolution and clarity. */
const SERVICE_COVERS: Partial<Record<ServiceSlug, string>> = {
  'glow-sign-boards': 'havells-015',
  'acp-led-signage': 'supreme-pipe-064',
  'flex-printing': 'captain-tmt-bar-072',
  'vehicle-branding': 'toptech-tmt-047',
  'wall-painting': 'sel-tmt-058',
  'f-pole-installation': 'sel-tmt-055',
  'in-shop-branding': 'toptech-tmt-040',
  'events-and-puja': 'supreme-pipe-085',
  'product-display': 'havells-020',
}

export function clientSlug(client: string): string {
  return client.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export function getPhotoById(id: string): GalleryPhoto {
  const photo = photos.find(p => p.id === id)
  if (!photo) throw new Error(`Missing gallery photo: ${id}`)
  return photo
}

export function getFeaturedPhotos(): GalleryPhoto[] {
  return photos.filter(p => p.featured)
}

export function getPhotosByService(service: ServiceSlug): GalleryPhoto[] {
  return photos.filter(p => p.service === service)
}

export function getPhotosByCity(city: CitySlug): GalleryPhoto[] {
  return photos.filter(p => p.city === city)
}

export function getPhotosByClient(slug: string): GalleryPhoto[] {
  return photos.filter(p => clientSlug(p.client) === slug)
}

export function getServiceCover(service: ServiceSlug): GalleryPhoto | undefined {
  const id = SERVICE_COVERS[service]
  return (id && photos.find(p => p.id === id)) || photos.find(p => p.service === service)
}

/** Brands with at least one photo, most photographed first. */
export function getClients(): { slug: string; name: string; count: number }[] {
  const counts = new Map<string, { slug: string; name: string; count: number }>()
  for (const p of photos) {
    const slug = clientSlug(p.client)
    const current = counts.get(slug) ?? { slug, name: p.client, count: 0 }
    current.count += 1
    counts.set(slug, current)
  }
  return [...counts.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
}
